source 'https://github.com/CocoaPods/Specs.git'
# source 'https://jihulab.com/yaya-ios/yayaspec.git'

# def jihu; return 'https://jihulab.com/yaya-ios/'; end
# def remotePod(name)
#    pod name, :git => jihu+"#{name}.git",:branch=>'dev'
# end

# def _localPod(name)
#    pod name, :path => "../../#{name}"
# end

use_frameworks!

platform :ios, '10.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
