#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

#source 'https://cdn.cocoapods.org/'

require './podVariables.rb'

use_frameworks!

platform :ios, '12.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  #_localPod 'SHMediator'
  #remotePod 'SHMediator'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
