source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'

require './podVariables.rb'

use_frameworks!

platform :ios, '10.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  #_localPod 'SHMediator'
  #remotePod 'SHMediator'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
